# Generated by Django 4.0.6 on 2025-08-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ust', 'Ustno'), ('pis', 'Pismeno')], max_length=5)),
                ('stage', models.IntegerField(choices=[(0, 'announced'), (1, 'rating'), (2, 'sale'), (3, 'distributed')], default=0)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('stage', models.IntegerField(choices=[(0, 'announced'), (1, 'rating'), (2, 'sale'), (3, 'distributed')], default=0)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DatumDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField()),
                ('reason', models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked'), ('justice', 'Justice')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.PositiveIntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'requested'), (1, 'responsed'), (2, 'accepted'), (3, 'rejected')], default=0)),
                ('datum_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_a', to='assessments.datum')),
                ('datum_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_b', to='assessments.datum')),
                ('student_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_requested', to='students.student')),
                ('student_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_received', to='students.student')),
            ],
        ),
    ]
