# Generated by Django 4.0.6 on 2025-08-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('schedules', '0001_initial'),
        ('assessments', '0001_initial'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap', to='logs.transactionlog'),
        ),
        migrations.AddField(
            model_name='datumdiscount',
            name='datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.datum'),
        ),
        migrations.AddField(
            model_name='datumdiscount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='datum',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datums', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='datum',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='class_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesments', to='students.class'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.subject'),
        ),
    ]
