# Generated by Django 4.0.6 on 2025-08-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datum',
            old_name='assessment',
            new_name='assessment_ref',
        ),
    ]
