# Generated by Django 4.0.6 on 2025-08-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_rename_assessment_datum_assessment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datum',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datum',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
