# Generated by Django 4.0.6 on 2025-08-08 16:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('datum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.datum')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='SwapLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_price', models.PositiveIntegerField()),
                ('new_status', models.IntegerField(choices=[(0, 'requested'), (1, 'responsed'), (2, 'accepted'), (3, 'rejected')], default=0)),
                ('message', models.TextField(blank=True)),
                ('swap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assessments.swap')),
            ],
        ),
        migrations.CreateModel(
            name='RatingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(-1, '-1'), (1, '+1')])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.datum')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='PenaltyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'penalty'), (1, 'cancellation')], default=0)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='JusticeCoefficientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_jc', models.FloatField()),
                ('to_jc', models.FloatField()),
                ('way', models.CharField(choices=[('random', 'Random Datum'), ('rated', 'Rated Datum')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('datum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justice_logs', to='assessments.datum')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justice_logs', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='DatumLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_date', models.DateField(blank=True, null=True)),
                ('current_label', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('current_stage', models.IntegerField(choices=[(0, 'announced'), (1, 'rating'), (2, 'sale'), (3, 'distributed')], default=0)),
                ('update', models.CharField(blank=True, choices=[('sold', 'Sold'), ('rated', 'Rated'), ('swapped', 'Swapped'), ('changed', 'Changed')], max_length=20)),
                ('datum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assessments.datum')),
                ('from_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datumlog_from', to='students.student')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datum_logs', to='logs.ratinglog')),
                ('swap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datum_logs', to='assessments.swap')),
                ('to_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datumlog_to', to='students.student')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datum_logs', to='logs.transactionlog')),
            ],
        ),
        migrations.CreateModel(
            name='ClassLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('update_type', models.CharField(choices=[('student', 'Student Changed'), ('name', 'Class Name Changed'), ('president', 'President Changed')], max_length=10)),
                ('current_name', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='students.class')),
                ('new_president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classlog_president', to='students.student')),
                ('new_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classlog_student', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_before', models.IntegerField()),
                ('stage_after', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
            ],
        ),
    ]
