# Generated by Django 4.0.6 on 2025-08-07 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assesments', '0001_initial'),
        ('logs', '0001_initial'),
        ('students', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap', to='logs.transactionlog'),
        ),
        migrations.AddField(
            model_name='datumdiscount',
            name='datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assesments.datum'),
        ),
        migrations.AddField(
            model_name='datumdiscount',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='datum',
            name='assesment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datums', to='assesments.assesment'),
        ),
        migrations.AddField(
            model_name='datum',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student'),
        ),
        migrations.AddField(
            model_name='assesment',
            name='class_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesments', to='students.class'),
        ),
        migrations.AddField(
            model_name='assesment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.subject'),
        ),
    ]
